In [1]:
import numpy as np
import pandas as pd
import os
import sys
import pickle
import time
import datetime
import matplotlib.pyplot as plt
import seaborn as sns
from importlib import reload
%matplotlib inline
from IPython.core.display import display, HTML, clear_output
display(HTML("<style>.container { width:80% !important; }</style>"))

# Load Content Embeddings

In [2]:
cwd = os.getcwd()
content_embeddings = pd.read_pickle("autoencoder_content_embeddings.pkl")
content_embeddings = pd.DataFrame(content_embeddings)
print(content_embeddings.shape)
content_embeddings.head()

(10677, 100)

,0,1,2,3,4,5,6,7,8,9,...,90,91,92,93,94,95,96,97,98,99
0,0.0,0.0,0.904098,0.0,0.0,0.000000,0.0,0.0,0.371671,0.135671,...,0.0,0.0,0.000000,0.0,0.123268,0.0,0.00000,0.000000,0.0,0.282723
1,0.0,0.0,0.353516,0.0,0.0,0.408598,0.0,0.0,0.249506,0.170421,...,0.0,0.0,0.542513,0.0,0.249089,0.0,0.00000,0.000000,0.0,0.231036
2,0.0,0.0,0.041036,0.0,0.0,0.283336,0.0,0.0,0.259030,0.398274,...,0.0,0.0,0.168425,0.0,0.000000,0.0,0.06342,0.000399,0.0,0.278501
3,0.0,0.0,0.124208,0.0,0.0,0.361411,0.0,0.0,0.095483,0.061589,...,0.0,0.0,0.271468,0.0,0.265663,0.0,0.00000,0.000000,0.0,0.437809
4,0.0,0.0,0.000000,0.0,0.0,1.052693,0.0,0.0,0.000000,0.192286,...,0.0,0.0,0.000000,0.0,1.136374,0.0,0.00000,0.052624,0.0,0.601307

# Load Collaborative Embeddings

In [3]:
cwd = os.getcwd()
collaborative_embeddings = pd.read_pickle("autoencoder_collaborative_embeddings.pkl")
collaborative_embeddings = pd.DataFrame(collaborative_embeddings)
print(collaborative_embeddings.shape)
collaborative_embeddings.head()

(10677, 100)

,0,1,2,3,4,5,6,7,8,9,...,90,91,92,93,94,95,96,97,98,99
0,0.771788,0.000000,0.228966,0.000000,0.0,0.0,0.0,0.705060,0.0,0.0,...,0.0,0.0,0.325671,0.673818,0.0,1.182551,0.0,0.000000,0.000000,0.0
1,3.242252,2.030967,0.000000,0.535234,0.0,0.0,0.0,3.071702,0.0,0.0,...,0.0,0.0,0.000000,4.345582,0.0,0.000000,0.0,2.799272,0.000000,0.0
2,4.566839,0.552188,0.000000,3.194058,0.0,0.0,0.0,1.595870,0.0,0.0,...,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.0
3,1.596353,1.859030,0.000000,0.647866,0.0,0.0,0.0,3.500792,0.0,0.0,...,0.0,0.0,0.000000,2.519434,0.0,0.000000,0.0,2.181360,0.357360,0.0
4,3.442600,3.288711,0.000000,5.780180,0.0,0.0,0.0,8.629416,0.0,0.0,...,0.0,0.0,0.000000,0.235270,0.0,0.000000,0.0,1.174890,0.182784,0.0

# Load Hybrid Embeddings

In [4]:
cwd = os.getcwd()
#collaborative_embeddings = pd.read_pickle("movie_embeddings_2.pkl")
hyb_embeddings = pd.read_pickle("autoencoderhy_embeddings.pkl")
hyb_embeddings = pd.DataFrame(hyb_embeddings)
print(collaborative_embeddings.shape)
hyb_embeddings.head()

(10677, 100)

,0,1,2,3,4,5,6,7,8,9,...,90,91,92,93,94,95,96,97,98,99
0,1.543448,0.0,1.345337,0.000000,0.0,0.000000,0.000000,0.00000,0.0,0.0,...,0.958427,0.000000,0.0,0.000000,0.0,0.0,0.000000,0.109635,0.0,0.0
1,5.119898,0.0,0.957946,1.460441,0.0,0.000000,2.651709,0.00000,0.0,0.0,...,0.000000,0.000000,0.0,0.000000,0.0,0.0,1.468070,0.000000,0.0,0.0
2,7.871745,0.0,3.872526,0.000000,0.0,5.645627,0.000000,0.00000,0.0,0.0,...,0.000000,4.326801,0.0,0.000000,0.0,0.0,1.420263,0.000000,0.0,0.0
3,3.955150,0.0,3.868255,0.000000,0.0,0.000000,4.956443,0.00000,0.0,0.0,...,0.000000,0.000000,0.0,0.000000,0.0,0.0,1.677247,0.000000,0.0,0.0
4,1.935301,0.0,4.614785,0.000000,0.0,0.000000,7.329194,1.23502,0.0,0.0,...,4.696230,0.000000,0.0,4.471815,0.0,0.0,1.664686,0.000000,0.0,0.0

# Format Movie Lookup Data

In [5]:
# Load index mapping 
with open('movie_to_idx.pkl', 'rb') as handle:
    movie2idx = pickle.load(handle)

In [6]:
#movies = pd.read_csv("movies.csv")
movies = pd.read_csv("movies.dat", sep='::', header=None, engine='python', encoding='latin-1')
movies.columns=['movieId','title','genres']
print("{} unique movies in movies.csv".format(len(movies.movieId.unique())))

#ratings = pd.read_csv("ratings.csv")
ratings=pd.read_csv('ratings.dat', sep='::', header=None, engine='python', encoding='latin-1')
ratings.columns=['userId','movieId', 'rating', 'timestamp']
print("{} unique movies in ratings.csv".format(len(ratings.movieId.unique())))

movies = pd.merge(movies, ratings, on="movieId", how="inner")
movies.movieId = movies.movieId.apply(lambda x: movie2idx[x])

#get popularity
popularity = pd.DataFrame(movies[['userId', 'title', 'movieId']].groupby(['title', 'movieId']).agg(['count']))
popularity.reset_index(inplace=True)
popularity.columns = ['title', 'movieId', 'ratings_count']
popularity.sort_values('ratings_count', ascending=False, inplace=True)
movies = pd.merge(popularity[['movieId', 'ratings_count']], movies, on='movieId')
movies.reset_index(inplace=True)

#get average ratings
average_ratings = pd.DataFrame(movies[['rating', 'title', 'movieId']].groupby(['title', 'movieId']).agg(['mean']))
average_ratings.reset_index(inplace=True)
average_ratings.columns = ['title', 'movieId', 'avg_rating']
movies = pd.merge(average_ratings[['movieId', 'avg_rating']], movies, on='movieId')
movies.reset_index(inplace=True)


movies = movies[['movieId', 'title', 'genres', 'ratings_count', 'avg_rating']]
movies.drop_duplicates(inplace=True)
print("{} unique movies in embeddings".format(len(movies.movieId.unique())))
movies.set_index('movieId', inplace=True, drop=True)
movies.sort_index(ascending=True, inplace=True)
print(movies.shape)
movies.head(5)

10681 unique movies in movies.csv
10677 unique movies in ratings.csv
10677 unique movies in embeddings
(10677, 4)

,title,genres,ratings_count,avg_rating
movieId,,,,
0,Boomerang (1992),Comedy|Romance,2412,2.861318
1,"Net, The (1995)",Action|Crime|Thriller,14975,3.125209
2,Dumb & Dumber (1994),Comedy,17851,2.936950
3,Outbreak (1995),Action|Drama|Sci-Fi|Thriller,16075,3.418414
4,Stargate (1994),Action|Adventure|Sci-Fi,18925,3.349353

In [7]:
movies.to_csv('movie_demographics.csv')

In [8]:
movies.query('title == "Zodiac (2007)"')

                 title                genres  ratings_count  avg_rating
movieId
3854     Zodiac (2007)  Crime|Drama|Thriller           1147    3.713165

# Recommendations

In [9]:
from similarity import SimilarityPredictions

In [10]:
def lookup_movie_id_by_title(movie_title):
    return movies[movies.title.str.contains(movie_title)]

In [11]:
lookup_movie_id_by_title("Evil")

,title,genres,ratings_count,avg_rating
movieId,,,,
230,Touch of Evil (1958),Crime|Film-Noir|Thriller,2665,4.203940
409,Evil Dead II (Dead by Dawn) (1987),Action|Comedy|Fantasy|Horror,3952,3.792637
724,"Evil Dead, The (1981)",Fantasy|Horror,2532,3.661137
813,Resident Evil (2002),Action|Horror|Sci-Fi|Thriller,2133,3.052274
977,Resident Evil: Apocalypse (2004),Action|Horror|Sci-Fi|Thriller,1008,2.879960
2036,Midnight in the Garden of Good and Evil (1997),Comedy|Crime|Drama|Mystery,2846,3.229093
3599,"See No Evil, Hear No Evil (1989)",Comedy|Crime,410,3.100000
3756,Evil (Ondskan) (2003),Drama,225,3.746667
4882,See No Evil (2006),Horror,49,2.265306
5144,Force of Evil (1948),Film-Noir,184,3.758152
5387,Evil Under the Sun (1982),Crime|Drama|Mystery,110,3.545455
5693,Resident Evil: Extinction (2007),Action|Horror|Sci-Fi|Thriller,324,3.086420
6243,Deliver Us from Evil (2006),Documentary,112,3.799107
6402,Hear No Evil (1993),Thriller,29,2.706897
7368,Two Evil Eyes (1990),Horror,37,2.810811
7988,"Flower of Evil, The (La Fleur du Mal) (2003)",Drama,32,3.140625
8159,Prom Night IV: Deliver Us From Evil (1992),Horror,101,1.356436
8247,Evilspeak (1981),Horror|Sci-Fi,13,1.961538
8791,See No Evil (1971),Crime|Drama|Horror|Thriller,32,3.281250
8873,Evil Aliens (2005),Comedy|Horror|Sci-Fi,8,2.437500
9069,"Evil That Men Do, The (1984)",Action|Thriller,31,2.338710

In [12]:
lotr = 798
IceAge = 812
Cin = 1450
ED = 724 #Evil Dead
notebook = 67

In [13]:
def get_detailed_recs(movie_id, embeddings, file_path):
    #get similar movies
    sim_model = SimilarityPredictions(embeddings, similarity_metric="cosine")
    output = sim_model.predict_similar_items(seed_item=movie_id, n=20)
    similar_movies = pd.DataFrame(output)
    similar_movies.set_index('item_id', inplace=True)
    sim_df = pd.merge(movies, similar_movies, left_index=True, right_index=True)
    sim_df.sort_values('similarity_score', ascending=False, inplace=True)
    
    #save recs locally
    sim_df.head(20).to_csv(file_path, index=False, header=True)
    return sim_df.head(20)

## Lord of the Rings, Fellowship of the Ring

### Collaborative Recommendations

In [14]:
get_detailed_recs(ED, collaborative_embeddings, 'collaborative.csv')

,title,genres,ratings_count,avg_rating,similarity_score
724,"Evil Dead, The (1981)",Fantasy|Horror,2532,3.661137,1.000000
2072,Hellraiser (1987),Horror,1309,3.294500,0.881030
3666,Dead Alive (Braindead) (1992),Comedy|Fantasy|Horror,1284,3.671729,0.847977
409,Evil Dead II (Dead by Dawn) (1987),Action|Comedy|Fantasy|Horror,3952,3.792637,0.846397
2307,Ring (Ringu) (1998),Horror|Mystery|Thriller,1301,3.617602,0.830428
3343,Dawn of the Dead (1978),Action|Drama|Horror,1223,3.800899,0.816737
1315,Bad Taste (1987),Comedy|Horror|Sci-Fi,1050,3.508095,0.802024
1140,"Texas Chainsaw Massacre, The (1974)",Horror,1587,3.191556,0.798887
2361,Eraserhead (1977),Drama|Horror,1232,3.583198,0.784558
2196,Twin Peaks: Fire Walk with Me (1992),Drama|Mystery,1155,3.384416,0.781787
726,"Lost Boys, The (1987)",Comedy|Horror|Thriller,2907,3.579119,0.778303
1463,Akira (1988),Action|Adventure|Animation|Sci-Fi,4055,3.825277,0.772970
5035,"Return of the Living Dead, The (1985)",Comedy|Horror|Sci-Fi,560,3.289286,0.772835
871,28 Days Later (2002),Horror|Sci-Fi,4542,3.694298,0.772830
1655,Pi (1998),Sci-Fi|Thriller,4488,3.732620,0.767467
2073,Hellbound: Hellraiser II (1988),Horror,730,2.930137,0.763025
670,American Psycho (2000),Comedy|Crime|Drama|Horror|Mystery|Thriller,3940,3.368909,0.762602
3716,Day of the Dead (1985),Horror|Thriller,502,3.446215,0.760632
2096,Battle Royale (Batoru Rowaiaru) (2000),Action|Drama|Horror|Sci-Fi|Thriller,1768,3.804864,0.759799
3718,Bubba Ho-tep (2002),Comedy|Horror,1004,3.555279,0.758869

### Content Recommendations

In [15]:
get_detailed_recs(ED, content_embeddings, 'content.csv')

,title,genres,ratings_count,avg_rating,similarity_score
724,"Evil Dead, The (1981)",Fantasy|Horror,2532,3.661137,1.000000
5682,"Innocents, The (1961)",Drama|Horror|Thriller,197,3.819797,0.890814
446,Mimic (1997),Horror|Sci-Fi|Thriller,1807,2.780299,0.866677
409,Evil Dead II (Dead by Dawn) (1987),Action|Comedy|Fantasy|Horror,3952,3.792637,0.866316
4740,Children of the Corn III (1994),Horror,247,1.676113,0.865092
3697,Thesis (Tesis) (1996),Drama|Horror|Thriller,283,3.791519,0.858435
4878,Slither (2006),Comedy|Horror|Sci-Fi,282,3.109929,0.855539
3773,"Wicker Man, The (2006)",Drama|Horror|Mystery|Thriller,199,1.957286,0.854227
6601,Puppet Master (1989),Horror|Sci-Fi|Thriller,386,2.779793,0.853902
7254,Night of the Creeps (1986),Comedy|Horror|Sci-Fi,229,2.681223,0.851765
3484,"Ilsa, She Wolf of the SS (1974)",Horror,97,2.634021,0.849102
6049,Halloween (2007),Horror,145,2.982759,0.846434
935,Dawn of the Dead (2004),Action|Drama|Horror|Thriller,1742,3.553961,0.840691
5787,"Invasion, The (2007)",Action|Drama|Horror|Sci-Fi|Thriller,184,3.057065,0.834233
7426,Blacula (1972),Horror,53,2.386792,0.833801
5484,"Godzilla, King of the Monsters! (1956)",Horror|Sci-Fi,183,3.259563,0.829531
4482,Cannibal Holocaust (1980),Horror,165,3.154545,0.828171
1105,"Girl, Interrupted (1999)",Drama,2442,3.501024,0.827320
559,"Faculty, The (1998)",Horror|Sci-Fi,2990,2.786622,0.827148
7077,Neighbors (1981),Comedy,134,2.664179,0.827022

### Hybrid Recommendation

In [16]:
get_detailed_recs(ED, hyb_embeddings, 'hybrid.csv')

,title,genres,ratings_count,avg_rating,similarity_score
724,"Evil Dead, The (1981)",Fantasy|Horror,2532,3.661137,1.000000
3343,Dawn of the Dead (1978),Action|Drama|Horror,1223,3.800899,0.890217
3718,Bubba Ho-tep (2002),Comedy|Horror,1004,3.555279,0.856318
409,Evil Dead II (Dead by Dawn) (1987),Action|Comedy|Fantasy|Horror,3952,3.792637,0.855655
3666,Dead Alive (Braindead) (1992),Comedy|Fantasy|Horror,1284,3.671729,0.847677
3716,Day of the Dead (1985),Horror|Thriller,502,3.446215,0.843666
1315,Bad Taste (1987),Comedy|Horror|Sci-Fi,1050,3.508095,0.827886
5035,"Return of the Living Dead, The (1985)",Comedy|Horror|Sci-Fi,560,3.289286,0.822222
768,Meet the Feebles (1989),Animation|Comedy|Musical,463,3.353132,0.814320
935,Dawn of the Dead (2004),Action|Drama|Horror|Thriller,1742,3.553961,0.794500
2845,Videodrome (1983),Fantasy|Horror|Sci-Fi|Thriller,704,3.643466,0.794473
1140,"Texas Chainsaw Massacre, The (1974)",Horror,1587,3.191556,0.792735
2072,Hellraiser (1987),Horror,1309,3.294500,0.787026
871,28 Days Later (2002),Horror|Sci-Fi,4542,3.694298,0.785984
2307,Ring (Ringu) (1998),Horror|Mystery|Thriller,1301,3.617602,0.777018
2808,They Live (1988),Action|Sci-Fi|Thriller,676,3.474112,0.765005
3679,Suspiria (1977),Horror,387,3.587855,0.759556
3713,Tremors (1990),Comedy|Horror|Sci-Fi,1615,3.328793,0.756385
2732,Re-Animator (1985),Horror,1040,3.487981,0.754452
5337,Scanners (1981),Horror|Sci-Fi|Thriller,500,3.201000,0.747704